name: Java Spring Boot CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build and Upload Artifact
        run: |
          mvn clean compile package -Dmaven.test.skip=true -Dspring-boot.run.profiles=prod
          mkdir staging && cp target/*.jar staging
          echo "DOCKER_IMAGE_TAG=spring-boot-login:$GITHUB_RUN_NUMBER" >> $GITHUB_ENV  # Store image tag in an environment variable
        # Upload the artifact without using deprecated 'save-state'
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
            name: java-jar-artifact
            path: staging

  create-docker-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: java-jar-artifact
          path: staging

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build . --file Dockerfile --tag $DOCKER_IMAGE_TAG .
          docker push $DOCKER_IMAGE_TAG
