name: Java Spring Boot CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn clean compile package -Dmaven.test.skip=true -Dspring-boot.run.profiles=prod
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - uses: actions/upload-artifact@v2  # Upload the artifact to be passed to the next job
        with:
          name: java-jar-artifact
          path: staging

  create-docker-image:
    needs: build  # Specify that create docker image depends on the 'build' job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: java-jar-artifact
          path: staging

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
