name: Java Spring Boot CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: mvn clean compile package -Dmaven.test.skip=true -Dspring-boot.run.profiles=prod
      - run: mkdir staging && cp target/*.jar staging

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
            name: java-jar-artifact
            path: staging

  create-docker-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: java-jar-artifact
          path: staging

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tag: laurapmedeiro/pwa-tfm:${{ github.sha }} 
